version: '3.5'
services:
  coordinator:
    image: digitalcredentials/issuer-coordinator:1.0.0
    env_file:
      - ./.coordinator.env
    ports:
      - "4005:4005"
  signer:
    image: digitalcredentials/signing-service:1.0.0
    env_file:
      - ./.signing-service.env
  status:
    image: digitalcredentials/status-service-db:0.1.0
    # image: digitalcredentials/status-service-git:0.1.0
    env_file:
      - ./.status-service-db.env
      # - ./.status-service-git.env
